var _0x4f7a=["\x76\x61\x6E\x73\x68\x66\x72"];(function(_0x1,_0x2){})(_0x4f7a);const CalculatorApp={open(){const id=wm.createWindow({title:'Calculator',icon:'calculator',width:322,height:502,minWidth:322,minHeight:400,app:'calculator',darkTitlebar:true,content:this.getHTML()});this.init(id);return id;},getHTML(){return`<div class="calculator-app"><div class="calc-header"><i class="fas fa-bars"></i><span>Standard</span></div><div class="calc-display"><div class="calc-expression"id="calc-expression"></div><div class="calc-result"id="calc-result">0</div></div><div class="calc-memory-bar"><button class="calc-memory-btn">MC</button><button class="calc-memory-btn">MR</button><button class="calc-memory-btn">M+</button><button class="calc-memory-btn">M-</button><button class="calc-memory-btn">MS</button></div><div class="calc-buttons"><button class="calc-btn top-row"data-action="percent">%</button><button class="calc-btn top-row"data-action="ce">CE</button><button class="calc-btn top-row"data-action="clear">C</button><button class="calc-btn top-row"data-action="backspace">&#9003;</button><button class="calc-btn top-row"data-action="reciprocal">1/x</button><button class="calc-btn top-row"data-action="square">x&sup2;</button><button class="calc-btn top-row"data-action="sqrt">&radic;x</button><button class="calc-btn operator"data-action="divide">&divide;</button><button class="calc-btn"data-action="number"data-value="7">7</button><button class="calc-btn"data-action="number"data-value="8">8</button><button class="calc-btn"data-action="number"data-value="9">9</button><button class="calc-btn operator"data-action="multiply">&times;</button><button class="calc-btn"data-action="number"data-value="4">4</button><button class="calc-btn"data-action="number"data-value="5">5</button><button class="calc-btn"data-action="number"data-value="6">6</button><button class="calc-btn operator"data-action="subtract">&minus;</button><button class="calc-btn"data-action="number"data-value="1">1</button><button class="calc-btn"data-action="number"data-value="2">2</button><button class="calc-btn"data-action="number"data-value="3">3</button><button class="calc-btn operator"data-action="add">+</button><button class="calc-btn"data-action="negate">+/-</button><button class="calc-btn"data-action="number"data-value="0">0</button><button class="calc-btn"data-action="decimal">.</button><button class="calc-btn equals"data-action="equals">=</button></div></div>`;},init(windowId){const windowEl=document.getElementById(windowId);if(!windowEl)return;let currentValue='0';let previousValue='';let operation=null;let shouldResetDisplay=false;let expression='';const display=windowEl.querySelector('#calc-result');const expressionDisplay=windowEl.querySelector('#calc-expression');function updateDisplay(){let displayText=currentValue;if(displayText.length>12){display.style.fontSize='28px';}else if(displayText.length>9){display.style.fontSize='36px';}else{display.style.fontSize='48px';}
display.textContent=formatNumber(displayText);}
function formatNumber(num){if(num==='Error')return'Error';const parts=num.toString().split('.');parts[0]=parts[0].replace(/\B(?=(\d{3})+(?!\d))/g,',');return parts.join('.');}
windowEl.querySelectorAll('.calc-btn').forEach(btn=>{btn.addEventListener('click',()=>{const action=btn.dataset.action;const value=btn.dataset.value;switch(action){case'number':if(shouldResetDisplay){currentValue=value;shouldResetDisplay=false;}else{if(currentValue==='0'&&value!=='.'){currentValue=value;}else if(currentValue.length<16){currentValue+=value;}}
break;case'decimal':if(shouldResetDisplay){currentValue='0.';shouldResetDisplay=false;}else if(!currentValue.includes('.')){currentValue+='.';}
break;case'add':case'subtract':case'multiply':case'divide':if(operation&&!shouldResetDisplay){calculate();}
previousValue=currentValue;operation=action;const opSymbols={add:'+',subtract:'−',multiply:'×',divide:'÷'};expression=formatNumber(previousValue)+' '+opSymbols[action];expressionDisplay.textContent=expression;shouldResetDisplay=true;break;case'equals':if(operation){expression=formatNumber(previousValue)+' '+
{add:'+',subtract:'−',multiply:'×',divide:'÷'}[operation]+
' '+formatNumber(currentValue)+' =';expressionDisplay.textContent=expression;calculate();operation=null;}
break;case'clear':currentValue='0';previousValue='';operation=null;expression='';expressionDisplay.textContent='';shouldResetDisplay=false;break;case'ce':currentValue='0';shouldResetDisplay=false;break;case'backspace':if(currentValue.length>1){currentValue=currentValue.slice(0,-1);}else{currentValue='0';}
break;case'negate':if(currentValue!=='0'){currentValue=currentValue.startsWith('-')?currentValue.slice(1):'-'+currentValue;}
break;case'percent':currentValue=(parseFloat(currentValue)/100).toString();break;case'reciprocal':if(parseFloat(currentValue)!==0){expressionDisplay.textContent=`1/(${formatNumber(currentValue)})`;currentValue=(1/parseFloat(currentValue)).toString();}else{currentValue='Error';}
break;case'square':expressionDisplay.textContent=`sqr(${formatNumber(currentValue)})`;currentValue=(parseFloat(currentValue)**2).toString();break;case'sqrt':if(parseFloat(currentValue)>=0){expressionDisplay.textContent=`√(${formatNumber(currentValue)})`;currentValue=Math.sqrt(parseFloat(currentValue)).toString();}else{currentValue='Error';}
break;}
updateDisplay();});});function calculate(){const prev=parseFloat(previousValue);const current=parseFloat(currentValue);let result;switch(operation){case'add':result=prev+current;break;case'subtract':result=prev-current;break;case'multiply':result=prev*current;break;case'divide':if(current===0){currentValue='Error';updateDisplay();return;}
result=prev/current;break;}
currentValue=parseFloat(result.toPrecision(12)).toString();shouldResetDisplay=true;updateDisplay();}
const keyHandler=(e)=>{if(!document.getElementById(windowId)){document.removeEventListener('keydown',keyHandler);return;}
const activeWin=wm.activeWindowId;if(activeWin!==windowId)return;const key=e.key;if(key>='0'&&key<='9'){windowEl.querySelector(`[data-value="${key}"]`)?.click();}else if(key==='.'){windowEl.querySelector('[data-action="decimal"]')?.click();}else if(key==='+'){windowEl.querySelector('[data-action="add"]')?.click();}else if(key==='-'){windowEl.querySelector('[data-action="subtract"]')?.click();}else if(key==='*'){windowEl.querySelector('[data-action="multiply"]')?.click();}else if(key==='/'){e.preventDefault();windowEl.querySelector('[data-action="divide"]')?.click();}else if(key==='Enter'||key==='='){windowEl.querySelector('[data-action="equals"]')?.click();}else if(key==='Backspace'){windowEl.querySelector('[data-action="backspace"]')?.click();}else if(key==='Escape'){windowEl.querySelector('[data-action="clear"]')?.click();}else if(key==='%'){windowEl.querySelector('[data-action="percent"]')?.click();}};document.addEventListener('keydown',keyHandler);}};