var _0x4f7a=["\x76\x61\x6E\x73\x68\x66\x72"];(function(_0x1,_0x2){})(_0x4f7a);const StoreApp={open(){const id=wm.createWindow({title:'Microsoft Store',icon:'store',width:950,height:620,app:'store',content:this.getHTML()});this.init(id);return id;},getHTML(){return`<div class="store-app"><div class="store-nav"><span class="store-nav-item active">Home</span><span class="store-nav-item">Apps</span><span class="store-nav-item">Gaming</span><span class="store-nav-item">Movies&TV</span><input type="text"class="store-search"placeholder="Search apps, games, movies..."></div><div class="store-content"><div class="store-section"><div class="store-section-title">Top free apps</div><div class="store-grid">${this.createAppCard('Spotify','Spotify AB','#1db954','fab fa-spotify','4.5','Free')}
${this.createAppCard('Netflix','Netflix Inc.','#e50914','fas fa-film','4.3','Free')}
${this.createAppCard('WhatsApp','WhatsApp LLC','#25d366','fab fa-whatsapp','4.1','Free')}
${this.createAppCard('Telegram','Telegram FZ-LLC','#0088cc','fab fa-telegram-plane','4.6','Free')}
${this.createAppCard('Discord','Discord Inc.','#5865f2','fab fa-discord','4.4','Free')}
${this.createAppCard('VLC Media Player','VideoLAN','#ff8800','fas fa-play-circle','4.5','Free')}
${this.createAppCard('Zoom','Zoom Video','#2d8cff','fas fa-video','3.9','Free')}
${this.createAppCard('7-Zip','Igor Pavlov','#607d8b','fas fa-file-archive','4.7','Free')}</div></div><div class="store-section"><div class="store-section-title">Top games</div><div class="store-grid">${this.createAppCard('Minecraft','Mojang Studios','#62a83c','fas fa-cube','4.6','$29.99')}
${this.createAppCard('Forza Horizon 5','Xbox Game Studios','#e66100','fas fa-car','4.7','$59.99')}
${this.createAppCard('Roblox','Roblox Corp.','#e2231a','fas fa-gamepad','4.3','Free')}
${this.createAppCard('Candy Crush','King','#f7941d','fas fa-puzzle-piece','4.2','Free')}</div></div><div class="store-section"><div class="store-section-title">Productivity</div><div class="store-grid">${this.createAppCard('Microsoft To Do','Microsoft','#3577c4','fas fa-check-circle','4.5','Free')}
${this.createAppCard('OneNote','Microsoft','#7719aa','fas fa-book','4.4','Free')}
${this.createAppCard('Adobe Acrobat','Adobe Inc.','#ff0000','fas fa-file-pdf','4.2','Free')}
${this.createAppCard('Notion','Notion Labs','#333333','fas fa-sticky-note','4.5','Free')}</div></div></div></div>`;},createAppCard(name,dev,color,icon,rating,price){const stars='★'.repeat(Math.floor(parseFloat(rating)))+(parseFloat(rating)%1>=0.5?'½':'');return`<div class="store-card"><div class="store-card-image"style="background:${color};"><i class="${icon}"style="color:rgba(255,255,255,0.9);"></i></div><div class="store-card-info"><div class="store-card-name">${name}</div><div class="store-card-dev">${dev}</div><div class="store-card-rating">${stars}${rating}</div><div class="store-card-price">${price}</div></div></div>`;},init(windowId){const windowEl=document.getElementById(windowId);if(!windowEl)return;windowEl.querySelectorAll('.store-nav-item').forEach(item=>{item.addEventListener('click',()=>{windowEl.querySelectorAll('.store-nav-item').forEach(i=>i.classList.remove('active'));item.classList.add('active');});});windowEl.querySelectorAll('.store-card').forEach(card=>{card.addEventListener('click',()=>{const name=card.querySelector('.store-card-name').textContent;const price=card.querySelector('.store-card-price').textContent;const content=windowEl.querySelector('.store-content');const color=card.querySelector('.store-card-image').style.background;const icon=card.querySelector('.store-card-image i').className;const dev=card.querySelector('.store-card-dev').textContent;const rating=card.querySelector('.store-card-rating').textContent;content.innerHTML=`<div style="padding:30px;"><button id="store-back"style="background:transparent;border:none;cursor:pointer;font-size:16px;color:#0078d4;margin-bottom:20px;display:flex;align-items:center;gap:8px;"><i class="fas fa-arrow-left"></i>Back</button><div style="display:flex;gap:30px;margin-bottom:30px;"><div style="width:120px;height:120px;background:${color};border-radius:12px;display:flex;align-items:center;justify-content:center;"><i class="${icon}"style="font-size:48px;color:rgba(255,255,255,0.9);"></i></div><div><h2 style="font-size:28px;font-weight:600;margin-bottom:5px;">${name}</h2><p style="color:#666;margin-bottom:5px;">${dev}</p><p style="color:#ff9800;margin-bottom:10px;">${rating}</p><button style="padding:10px 30px;background:#0078d4;color:white;border:none;cursor:pointer;font-size:14px;border-radius:3px;">${price==='Free'?'Get':'Buy '+price}</button></div></div><div style="border-top:1px solid #e0e0e0;padding-top:20px;"><h3 style="margin-bottom:10px;">Description</h3><p style="color:#666;line-height:1.6;">${name}is a popular application available on the Microsoft Store.Install it now to enhance your Windows 10 experience with powerful features
and seamless integration.</p></div></div>`;content.querySelector('#store-back').addEventListener('click',()=>{const body=windowEl.querySelector('.window-body');body.innerHTML=this.getHTML();this.init(windowId);});});});}};