var _0x4f7a=["\x76\x61\x6E\x73\x68\x66\x72"];(function(_0x1,_0x2){})(_0x4f7a);class WindowManager{constructor(){this.windows=new Map();this.container=document.getElementById('windows-container');this.zIndex=100;this.activeWindowId=null;this.snapPreview=null;}
createWindow(options){const{id=Utils.generateId(),title='Window',icon='fas fa-window-maximize',width=800,height=500,minWidth=300,minHeight=200,x=null,y=null,content='',app='',darkTitlebar=false,resizable=true,maximized=false,onClose=null,onResize=null,onFocus=null}=options;const posX=x!==null?x:Math.max(50,Math.random()*(window.innerWidth-width-100));const posY=y!==null?y:Math.max(20,Math.random()*(window.innerHeight-height-140));const windowEl=document.createElement('div');windowEl.className=`app-window opening${darkTitlebar?' dark-titlebar':''}`;windowEl.id=id;windowEl.dataset.app=app;windowEl.style.width=width+'px';windowEl.style.height=height+'px';windowEl.style.left=posX+'px';windowEl.style.top=posY+'px';const iconHtml=(typeof Win10Icons!=='undefined'&&Win10Icons[icon])?Win10Icons.getSmall(icon,16):`<i class="${icon}"></i>`;windowEl.innerHTML=`<div class="title-bar"><div class="title-bar-icon">${iconHtml}</div><div class="title-bar-title">${title}</div><div class="window-controls"><button class="window-control minimize-btn"title="Minimize"><svg width="10"height="10"viewBox="0 0 10 10"><line x1="0"y1="5"x2="10"y2="5"stroke="currentColor"stroke-width="1"/></svg></button><button class="window-control maximize-btn"title="Maximize"><svg width="10"height="10"viewBox="0 0 10 10"><rect x="0.5"y="0.5"width="9"height="9"fill="none"stroke="currentColor"stroke-width="1"/></svg></button><button class="window-control close-btn"title="Close"><svg width="10"height="10"viewBox="0 0 10 10"><line x1="0"y1="0"x2="10"y2="10"stroke="currentColor"stroke-width="1"/><line x1="10"y1="0"x2="0"y2="10"stroke="currentColor"stroke-width="1"/></svg></button></div></div><div class="window-body">${content}</div>${resizable?`<div class="resize-handle top"></div><div class="resize-handle bottom"></div><div class="resize-handle left"></div><div class="resize-handle right"></div><div class="resize-handle top-left"></div><div class="resize-handle top-right"></div><div class="resize-handle bottom-left"></div><div class="resize-handle bottom-right"></div>`:''}`;this.container.appendChild(windowEl);const windowData={id,element:windowEl,title,app,isMaximized:false,isMinimized:false,prevBounds:null,minWidth,minHeight,onClose,onResize,onFocus};this.windows.set(id,windowData);this._setupWindowEvents(windowData);this.focusWindow(id);if(typeof Taskbar!=='undefined'){Taskbar.addWindow(id,app,title,icon);}
setTimeout(()=>windowEl.classList.remove('opening'),200);if(maximized){this.toggleMaximize(id);}
return id;}
_setupWindowEvents(windowData){const{element,id}=windowData;const titleBar=element.querySelector('.title-bar');const minimizeBtn=element.querySelector('.minimize-btn');const maximizeBtn=element.querySelector('.maximize-btn');const closeBtn=element.querySelector('.close-btn');element.addEventListener('mousedown',(e)=>{if(!e.target.closest('.window-control')){this.focusWindow(id);}});this._setupDrag(titleBar,windowData);element.querySelectorAll('.resize-handle').forEach(handle=>{this._setupResize(handle,windowData);});minimizeBtn.addEventListener('click',()=>this.minimizeWindow(id));maximizeBtn.addEventListener('click',()=>this.toggleMaximize(id));closeBtn.addEventListener('click',()=>this.closeWindow(id));titleBar.addEventListener('dblclick',(e)=>{if(!e.target.closest('.window-controls')){this.toggleMaximize(id);}});}
_setupDrag(titleBar,windowData){let isDragging=false;let startX,startY,startLeft,startTop;const{element,id}=windowData;titleBar.addEventListener('mousedown',(e)=>{if(e.target.closest('.window-controls')||e.target.closest('.title-bar-icon'))return;if(windowData.isMaximized){const rect=element.getBoundingClientRect();const percentX=(e.clientX-rect.left)/rect.width;this.toggleMaximize(id);const newRect=element.getBoundingClientRect();startLeft=e.clientX-(newRect.width*percentX);startTop=e.clientY-16;element.style.left=startLeft+'px';element.style.top=startTop+'px';}else{startLeft=element.offsetLeft;startTop=element.offsetTop;}
isDragging=true;startX=e.clientX;startY=e.clientY;this.focusWindow(id);document.body.style.userSelect='none';});document.addEventListener('mousemove',(e)=>{if(!isDragging)return;const dx=e.clientX-startX;const dy=e.clientY-startY;let newLeft=startLeft+dx;let newTop=startTop+dy;newTop=Math.max(0,newTop);element.style.left=newLeft+'px';element.style.top=newTop+'px';this._handleSnapDetection(e.clientX,e.clientY,windowData);});document.addEventListener('mouseup',(e)=>{if(!isDragging)return;isDragging=false;document.body.style.userSelect='';this._applySnap(e.clientX,e.clientY,windowData);this._removeSnapPreview();});}
_handleSnapDetection(x,y,windowData){const threshold=5;const screenW=window.innerWidth;const screenH=window.innerHeight-40;if(!this.snapPreview){this.snapPreview=document.createElement('div');this.snapPreview.className='snap-preview';document.getElementById('desktop').appendChild(this.snapPreview);}
if(x<=threshold){this.snapPreview.style.display='block';this.snapPreview.style.left='0';this.snapPreview.style.top='0';this.snapPreview.style.width=(screenW/2)+'px';this.snapPreview.style.height=screenH+'px';}else if(x>=screenW-threshold){this.snapPreview.style.display='block';this.snapPreview.style.left=(screenW/2)+'px';this.snapPreview.style.top='0';this.snapPreview.style.width=(screenW/2)+'px';this.snapPreview.style.height=screenH+'px';}else if(y<=threshold){this.snapPreview.style.display='block';this.snapPreview.style.left='0';this.snapPreview.style.top='0';this.snapPreview.style.width=screenW+'px';this.snapPreview.style.height=screenH+'px';}else{this.snapPreview.style.display='none';}}
_applySnap(x,y,windowData){const threshold=5;const screenW=window.innerWidth;const screenH=window.innerHeight-40;const{element,id}=windowData;if(x<=threshold){element.style.left='0';element.style.top='0';element.style.width=(screenW/2)+'px';element.style.height=screenH+'px';}else if(x>=screenW-threshold){element.style.left=(screenW/2)+'px';element.style.top='0';element.style.width=(screenW/2)+'px';element.style.height=screenH+'px';}else if(y<=threshold){if(!windowData.isMaximized){this.toggleMaximize(id);}}}
_removeSnapPreview(){if(this.snapPreview){this.snapPreview.remove();this.snapPreview=null;}}
_setupResize(handle,windowData){let isResizing=false;let startX,startY,startWidth,startHeight,startLeft,startTop;const direction=handle.className.replace('resize-handle ','');const{element}=windowData;handle.addEventListener('mousedown',(e)=>{if(windowData.isMaximized)return;e.preventDefault();e.stopPropagation();isResizing=true;startX=e.clientX;startY=e.clientY;startWidth=element.offsetWidth;startHeight=element.offsetHeight;startLeft=element.offsetLeft;startTop=element.offsetTop;document.body.style.userSelect='none';this.focusWindow(windowData.id);});document.addEventListener('mousemove',(e)=>{if(!isResizing)return;const dx=e.clientX-startX;const dy=e.clientY-startY;let newWidth=startWidth;let newHeight=startHeight;let newLeft=startLeft;let newTop=startTop;if(direction.includes('right'))newWidth=Math.max(windowData.minWidth,startWidth+dx);if(direction.includes('left')){newWidth=Math.max(windowData.minWidth,startWidth-dx);newLeft=startLeft+(startWidth-newWidth);}
if(direction.includes('bottom'))newHeight=Math.max(windowData.minHeight,startHeight+dy);if(direction.includes('top')){newHeight=Math.max(windowData.minHeight,startHeight-dy);newTop=startTop+(startHeight-newHeight);}
element.style.width=newWidth+'px';element.style.height=newHeight+'px';element.style.left=newLeft+'px';element.style.top=newTop+'px';if(windowData.onResize){windowData.onResize(newWidth,newHeight);}});document.addEventListener('mouseup',()=>{if(isResizing){isResizing=false;document.body.style.userSelect='';}});}
focusWindow(id){if(!this.windows.has(id))return;this.windows.forEach((win)=>{win.element.classList.remove('focused');});const windowData=this.windows.get(id);this.zIndex++;windowData.element.style.zIndex=this.zIndex;windowData.element.classList.add('focused');this.activeWindowId=id;if(typeof Taskbar!=='undefined'){Taskbar.setActiveWindow(id,windowData.app);}
if(windowData.onFocus)windowData.onFocus();}
minimizeWindow(id){const windowData=this.windows.get(id);if(!windowData)return;windowData.isMinimized=true;windowData.element.classList.add('minimized');let nextWindow=null;let highestZ=-1;this.windows.forEach((win,winId)=>{if(winId!==id&&!win.isMinimized){const z=parseInt(win.element.style.zIndex)||0;if(z>highestZ){highestZ=z;nextWindow=winId;}}});if(nextWindow){this.focusWindow(nextWindow);}else{this.activeWindowId=null;if(typeof Taskbar!=='undefined'){Taskbar.setActiveWindow(null);}}}
restoreWindow(id){const windowData=this.windows.get(id);if(!windowData)return;windowData.isMinimized=false;windowData.element.classList.remove('minimized');this.focusWindow(id);}
toggleMaximize(id){const windowData=this.windows.get(id);if(!windowData)return;const{element}=windowData;const maxBtn=element.querySelector('.maximize-btn');if(windowData.isMaximized){element.classList.remove('maximized');if(windowData.prevBounds){element.style.width=windowData.prevBounds.width;element.style.height=windowData.prevBounds.height;element.style.left=windowData.prevBounds.left;element.style.top=windowData.prevBounds.top;}
windowData.isMaximized=false;maxBtn.innerHTML='<svg width="10" height="10" viewBox="0 0 10 10"><rect x="0.5" y="0.5" width="9" height="9" fill="none" stroke="currentColor" stroke-width="1"/></svg>';}else{windowData.prevBounds={width:element.style.width,height:element.style.height,left:element.style.left,top:element.style.top};element.classList.add('maximized');windowData.isMaximized=true;maxBtn.innerHTML='<svg width="10" height="10" viewBox="0 0 10 10"><rect x="2.5" y="0.5" width="7" height="7" fill="none" stroke="currentColor" stroke-width="1"/><rect x="0.5" y="2.5" width="7" height="7" fill="#f0f0f0" stroke="currentColor" stroke-width="1"/></svg>';}
if(windowData.onResize){setTimeout(()=>{const rect=element.getBoundingClientRect();windowData.onResize(rect.width,rect.height);},50);}}
closeWindow(id){const windowData=this.windows.get(id);if(!windowData)return;windowData.element.classList.add('closing');setTimeout(()=>{if(windowData.onClose)windowData.onClose();windowData.element.remove();this.windows.delete(id);if(typeof Taskbar!=='undefined'){Taskbar.removeWindow(id,windowData.app);}
if(this.activeWindowId===id){let nextWindow=null;let highestZ=-1;this.windows.forEach((win,winId)=>{if(!win.isMinimized){const z=parseInt(win.element.style.zIndex)||0;if(z>highestZ){highestZ=z;nextWindow=winId;}}});if(nextWindow){this.focusWindow(nextWindow);}else{this.activeWindowId=null;}}},150);}
getWindowByApp(app){for(const[id,win]of this.windows){if(win.app===app)return id;}
return null;}
toggleWindow(id){const windowData=this.windows.get(id);if(!windowData)return;if(windowData.isMinimized){this.restoreWindow(id);}else if(this.activeWindowId===id){this.minimizeWindow(id);}else{this.focusWindow(id);}}
updateTitle(id,newTitle){const windowData=this.windows.get(id);if(!windowData)return;windowData.title=newTitle;windowData.element.querySelector('.title-bar-title').textContent=newTitle;}}
const wm=new WindowManager();